[theme]
base="dark"
primaryColor="#1f77b4"
backgroundColor="#121212"
secondaryBackgroundColor="#1f1f1f"
textColor="#ffffff"


[browser]
gatherUsageStats = false

[server]
headless = true


[ui]
hideTopBar = true

